/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include"i2c.h"
#include"lcd.h"
#include"lm35.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{	char str[40];
	LcdInit();
	LM35_Init();

	while(1)
	{
		float temp=LM35_ReadTemperature();   //read temp in oc 
		sprintf(str,"Temp %2.2f C",temp);   //format into the string 
		LcdPuts(LCD_LINE1, "MQT Reading");   // display heading on lcd
		LcdPuts(LCD_LINE2, str);             // show the temp
		DelayMs(500);                         //wait 500 ms       
	}

}

